# config.yaml
global_config:
  splits:
    - train
    - sub_train
    - valid_seen
    - valid_train
    - valid_unseen
  cases:
    - with_oracle
    - partial_oracle
    - no_oracle
  methods:
    - React
    - respact
  oracle_types:
    - Planner
    - Handcoded

sampled_data_file: 'data/experiments/data_sample.json' # path to sub-sampled data directory

env:
  type: "AlfredTWEnv"
  
experiments:
  Respact-Org:
      name: 'helpful-user-train' 
      split: 'eval_out_of_distribution'
      method: 'respact'
      agent: 'gpt4_agent'
      main_prompt_file: None
      method_prompt_file: 'prompts/respact_alfred.json'
      oracle: True
      version: 'original'

  Respact-Opt:
    name: 'helpful-user-train' 
    split: 'eval_out_of_distribution'
    method: 'respact'
    agent: 'gpt4_agent'
    main_prompt_file: prompts/main_prompt_respact.txt
    method_prompt_file: 'prompts/respact_alfred_updated.json'
    oracle: True
    version: 'original'

  React-Org_01_P:  
    name: 'React' 
    split: 'eval_out_of_distribution'
    method: 'React'
    agent: 'gpt4_agent'
    main_prompt_file: None
    method_prompt_file: 'prompts/alfworld_3prompts.json'
    oracle: False
    version: 'original'

  React-Opt_21:  
    name: 'React' 
    split: 'eval_out_of_distribution'
    method: 'React'
    agent: 'gpt4_agent'
    main_prompt_file: prompts/main_prompt.txt
    method_prompt_file: 'prompts/alfworld_3prompts.json'
    oracle: False
    version: 'original'