# config.yaml
global_config:
  splits:
    - train
    - sub_train
    - valid_seen
    - valid_train
    - valid_unseen
  cases:
    - with_oracle
    - partial_oracle
    - no_oracle
  methods:
    - React
    - respact
  oracle_types:
    - Planner
    - Handcoded

sampled_data_file: 'data/experiments/data_sample.json' # path to sub-sampled data directory

env:
  type: "AlfredTWEnv"
  
experiments:

  experiment_0_case_1: # Case-1: Helpful Perfect User
    name: 'helpful-user-train' 
    split: 'train'
    method: 'respact'
    agent: 'gpt4_agent'
    main_prompt_file: prompts/main_prompt_opt.txt
    method_prompt_file: 'prompts/respact_alfred_updated.json'
    oracle: True

  experiment_0_case_1_1: # Case-1_1: Helpful Perfect User with GPT-3
    name: 'helpful-user-train' 
    split: 'train'
    method: 'respact'
    agent: 'gpt3_agent'
    main_prompt_file: prompts/main_prompt.txt
    method_prompt_file: 'prompts/respact_alfred.json'
    oracle: True

  experiment_0_case_1_2: # Case-1_2: Helpful Perfect User with LLAMA 3-70B Instruct
    name: 'helpful-user-train' 
    split: 'train'
    method: 'respact'
    agent: 'llama3_agent'
    main_prompt_file: prompts/main_prompt.txt
    method_prompt_file: 'prompts/respact_alfred.json'
    oracle: True

  experiment_0_case_1_3: # Case-1_3: Helpful Perfect User with LLAMA 3.1 Instruct
    name: 'helpful-user-train' 
    split: 'train'
    method: 'respact'
    agent: 'llama31_agent'
    main_prompt_file: prompts/main_prompt.txt
    method_prompt_file: 'prompts/respact_alfred.json'
    oracle: True

  experiment_0_case_1_4: # Case-1_4: Helpful Perfect User with MISTRAL 7B
    name: 'helpful-user-train' 
    split: 'train'
    method: 'respact'
    agent: 'mistral_agent'
    main_prompt_file: prompts/main_prompt.txt
    method_prompt_file: 'prompts/respact_alfred.json'
    oracle: True

  experiment_1_case_1:  
    name: 'helpful-user-train' 
    split: 'train'
    method: 'React'
    agent: 'gpt4_agent'
    main_prompt_file: prompts/main_prompt.txt
    method_prompt_file: 'prompts/alfworld_3prompts.json'
    oracle: False

  experiment_1_case_1_1: # Case-1_1: Helpful Perfect User with GPT-3
    name: 'helpful-user-train' 
    split: 'train'
    method: 'React'
    agent: 'gpt3_agent'
    main_prompt_file: prompts/main_prompt.txt
    method_prompt_file: 'prompts/alfworld_3prompts.json'
    oracle: False

  experiment_1_case_1_2: # Case-1_2: Helpful Perfect User with LLAMA 3-70B Instruct
    name: 'helpful-user-train' 
    split: 'train'
    method: 'React'
    agent: 'llama3_agent'
    main_prompt_file: prompts/main_prompt.txt
    method_prompt_file: 'prompts/alfworld_3prompts.json'
    oracle: False

  experiment_1_case_1_3: # Case-1_3: Helpful Perfect User with LLAMA 3.1 Instruct
    name: 'helpful-user-train' 
    split: 'train'
    method: 'React'
    agent: 'llama31_agent'
    main_prompt_file: prompts/main_prompt.txt
    method_prompt_file: 'prompts/alfworld_3prompts.json'
    oracle: False

  experiment_1_case_1_4: # Case-1_4: Helpful Perfect User with MISTRAL 7B
    name: 'helpful-user-train' 
    split: 'train'
    method: 'React'
    agent: 'mistral_agent'
    main_prompt_file: 'prompts/react_main_prompt_opt.txt'
    method_prompt_file: 'prompts/alfworld_3prompts_updated.json'
    oracle: False

  experiment_0_case_2:
    name: 'noisy-user-train' 
    split: 'train'
    method: 'respact'
    agent: 'gpt4_agent'
    main_prompt_file: prompts/main_prompt.txt
    prompt_file: 'prompts/respact_alfred.json'
    oracle: True

  experiment_0_case_3:
    name: 'unhelpful-user-train' 
    split: 'train'
    method: 'respact'
    agent: 'gpt4_agent'
    main_prompt_file: prompts/main_prompt.txt
    prompt_file: 'prompts/alfworld_3prompts.json'
    oracle: False

  experiment_2_case_1:
    name: 'better-speak-acts-train' 
    split: 'train'
    method: 'respact'
    agent: 'gpt4_agent'
    main_prompt_file: prompts/main_prompt.txt
    prompt_file: 'prompts/respact_alfred.json'
    oracle: True

  experiment_00_case_1: # Case-1: Helpful Perfect User
    name: 'helpful-user-train' 
    split: 'train'
    method: 'respact'
    agent: 'gpt4_structured_agent'
    main_prompt_file: prompts/main_prompt_opt.txt
    method_prompt_file: 'prompts/respact_alfred_updated.json'
    oracle: True
  
  experiment_01_case_1: # Case-1: Helpful Perfect User
    name: 'helpful-user-train' 
    split: 'train'
    method: 'React'
    agent: 'gpt4_structured_agent'
    main_prompt_file: 'prompts/main_prompt_opt.txt'
    method_prompt_file: 'prompts/alfworld_3prompts_updated.json'
    oracle: False


run_configs:
  selected_experiments:
    - experiment_1_case_1_4
   
    




